'use strict';
var _ = require('underscore');

var _INFO_FOUND= 'INFO_FOUND';
var _INFO_NOT_FOUND=  'INFO_NOT_FOUND';
var _MISSING_PARAMETERS=  'MISSING_PARAMETERS';
var _SUCESSFUL= 'SUCESSFUL';
var _DUPLICATE_DATA= 'DUPLICATE_DATA';

exports.INFO_FOUND= _INFO_FOUND;
exports.INFO_NOT_FOUND= _INFO_NOT_FOUND;
exports.MISSING_PARAMETERS= _MISSING_PARAMETERS;
exports.SUCESSFUL= _SUCESSFUL;
exports.DUPLICATE_DATA= _DUPLICATE_DATA;